repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: forbid-new-submodules
-   repo: https://github.com/myint/docformatter
    -   id: docformatter
        name: docformatter
        description: 'Formats docstrings to follow PEP 257.'
        entry: docformatter
        args: [-i]
        language: python
        types: [python]