repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: forbid-new-submodules
    -   id: flake8
-   repo: https://github.com/myint/docformatter
    rev: v1.3
    hooks:
    -   id: docformatter
