"""A setuptools based setup module.

See:
https://packaging.python.org/en/latest/distributing.html
https://github.com/pypa/sampleproject
Autogenerated by poetry-setup:
https://github.com/orsinium/poetry-setup
"""
# IMPORTANT: this file is autogenerated. Do not edit it manually.
# All changes will be lost after `poetry-setup` command execution.
# ----------------------------------------------------------------
# Always prefer setuptools over distutils
from io import open
from os import path

from setuptools import find_packages
from setuptools import setup

# io.open is needed for projects that support Python 2.7
# It ensures open() defaults to text mode with universal newlines,
# and accepts an argument to specify the text encoding
# Python 3 only projects can skip this import

here = path.abspath(path.dirname(__file__))
# Get the long description from the README file

# Arguments marked as "Required" below must be included for upload to PyPI.
# Fields marked as "Optional" may be commented out.
setup(
    # https://packaging.python.org/specifications/core-metadata/#name
    name="dasi",  # Required
    # https://www.python.org/dev/peps/pep-0440/
    # https://packaging.python.org/en/latest/single_source_version.html
    version="0.0.1",  # Required
    # https://packaging.python.org/specifications/core-metadata/#summary
    description="",  # Required
    # https://packaging.python.org/specifications/core-metadata/#description-optional
    # https://packaging.python.org/specifications/core-metadata/#description-content-type-optional
    long_description_content_type="text/markdown",  # Optional (see note above)
    author="jvrana",  # Optional
    author_email="justin.vrana@gmail.com",  # Optional
    # For a list of valid classifiers, see https://pypi.org/classifiers/
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
    ],  # Optional
    packages=find_packages(),  # Required
    # https://packaging.python.org/en/latest/requirements.html
    install_requires=[
        "networkx (>=2.3,<3.0)",
        "more-itertools (>=7.1,<8.0)",
        "tqdm (>=4.32,<5.0)",
        "sortedcontainers (>=2.1,<3.0)",
        "loggable-jdv (>=0.1.2,<0.2.0)",
        "uvloop (>=0.12.2,<0.13.0)",
        "nest_asyncio (>=1.0,<2.0)",
        "pyblastbio (>=0.2.10,<0.3.0)",
    ],  # Optional
    # https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi
    dependency_links=[],  # Optional
    # https://stackoverflow.com/a/16576850
    include_package_data=True,
    # https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use
    project_urls={},  # Optional
)
