# __version__.py
# autogenerated by keats 0.2.23
__version__ = "0.0.1"
__name__ = "shoestring"
__title__ = "shoestring"
__authors__ = ['jvrana <justin.vrana@gmail.com>']
__repo__ = None
__homepage__ = None
__description__ = ""
