# __version__.py

# autogenerated by keats 0.2.29

__version__ = "0.2.1"
__name__ = "dasi"
__title__ = "dasi"
__authors__ = ['Justin Vrana <justin.vrana@gmail.com>']
__repository__ = None
__homepage__ = "https://github.com/jvrana/dasi-dna-design"
__description__ = "Automated DNA assembly planner for Python"
__license__ = None
__maintainers__ = None
__readme__ = "README.md"